### ISSUE TITLE
[Intro to iOS] Project 1: Rotten Tomatoes

### ISSUE THREAD

**Issue by niazjalal** [niazjalal/ios_bootcamp_rottentomatoes#1]
My first project assignment submission.  -- Niaz

added readme and animated gif

updated with all required tasks, updated read me 2, updated demo gif 2

/cc @thecodepath

**Comment by timothy1ee** [comment]
Niaz, for the error view, you need to implement this yourself without a library. You should add an error view (a view and a label) in the Storyboard. Show this error view (use the hidden property) if there is a network error or hide it if the network request succeeds.

**Comment by niazjalal** [comment]
I see would you like me to redo that part?  Thanks for the feedback.

**Comment by niazjalal** [comment]
Completed.
